#
# Josh Hursey
# CS 441/541: Project 4 Given Tests
#

check: pagefault banner_help \
	check-level-1 check-level-2 check-level-3 \
	check-level-4 check-level-5 check-level-6 check-level-7

banner_help:
	@echo "By default check will run all levels."
	@echo "You can run an individual level by using one of the following:"
	@echo "   check-level-1"
	@echo "   check-level-2"
	@echo "   check-level-3"
	@echo "   check-level-4"
	@echo "   check-level-5"
	@echo "   check-level-6"
	@echo "   check-level-7"
	@echo ""
	@sleep 1

###############################################
# Tests - Level 1
###############################################
LEVEL_1_INPUT=given-tests/level1.txt
check-level-1: pagefault banner_1 \
	check-level-1-f-0 check-level-1-f-1 check-level-1-f-2 check-level-1-f-3 \
	check-level-1-f-4 check-level-1-f-5 check-level-1-f-6 check-level-1-f-7

banner_1:
	@echo ""
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@echo "mmmmmmmmm Level 1 Tests mmmmmmmmmmm"
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@sleep 1

LEVEL_1_EXP_F_0=given-tests/level1-exp-f-0.txt
check-level-1-f-0: pagefault
	@given-tests/check.pl 0 $(LEVEL_1_INPUT) $(LEVEL_1_EXP_F_0)

LEVEL_1_EXP_F_1=given-tests/level1-exp-f-1.txt
check-level-1-f-1: pagefault
	@given-tests/check.pl 1 $(LEVEL_1_INPUT) $(LEVEL_1_EXP_F_1)

LEVEL_1_EXP_F_2=given-tests/level1-exp-f-2.txt
check-level-1-f-2: pagefault
	@given-tests/check.pl 2 $(LEVEL_1_INPUT) $(LEVEL_1_EXP_F_2)

LEVEL_1_EXP_F_3=given-tests/level1-exp-f-3.txt
check-level-1-f-3: pagefault
	@given-tests/check.pl 3 $(LEVEL_1_INPUT) $(LEVEL_1_EXP_F_3)

LEVEL_1_EXP_F_4=given-tests/level1-exp-f-4.txt
check-level-1-f-4: pagefault
	@given-tests/check.pl 4 $(LEVEL_1_INPUT) $(LEVEL_1_EXP_F_4)

LEVEL_1_EXP_F_5=given-tests/level1-exp-f-5.txt
check-level-1-f-5: pagefault
	@given-tests/check.pl 5 $(LEVEL_1_INPUT) $(LEVEL_1_EXP_F_5)

LEVEL_1_EXP_F_6=given-tests/level1-exp-f-6.txt
check-level-1-f-6: pagefault
	@given-tests/check.pl 6 $(LEVEL_1_INPUT) $(LEVEL_1_EXP_F_6)

LEVEL_1_EXP_F_7=given-tests/level1-exp-f-7.txt
check-level-1-f-7: pagefault
	@given-tests/check.pl 7 $(LEVEL_1_INPUT) $(LEVEL_1_EXP_F_7)

###############################################
# Tests - Level 2
###############################################
LEVEL_2_INPUT=given-tests/level2.txt
check-level-2: pagefault banner_2 \
	check-level-2-f-0 check-level-2-f-1 check-level-2-f-2 check-level-2-f-3 \
	check-level-2-f-4 check-level-2-f-5 check-level-2-f-6 check-level-2-f-7

banner_2:
	@echo ""
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@echo "mmmmmmmmm Level 2 Tests mmmmmmmmmmm"
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@sleep 1

LEVEL_2_EXP_F_0=given-tests/level2-exp-f-0.txt
check-level-2-f-0: pagefault
	@given-tests/check.pl 0 $(LEVEL_2_INPUT) $(LEVEL_2_EXP_F_0)

LEVEL_2_EXP_F_1=given-tests/level2-exp-f-1.txt
check-level-2-f-1: pagefault
	@given-tests/check.pl 1 $(LEVEL_2_INPUT) $(LEVEL_2_EXP_F_1)

LEVEL_2_EXP_F_2=given-tests/level2-exp-f-2.txt
check-level-2-f-2: pagefault
	@given-tests/check.pl 2 $(LEVEL_2_INPUT) $(LEVEL_2_EXP_F_2)

LEVEL_2_EXP_F_3=given-tests/level2-exp-f-3.txt
check-level-2-f-3: pagefault
	@given-tests/check.pl 3 $(LEVEL_2_INPUT) $(LEVEL_2_EXP_F_3)

LEVEL_2_EXP_F_4=given-tests/level2-exp-f-4.txt
check-level-2-f-4: pagefault
	@given-tests/check.pl 4 $(LEVEL_2_INPUT) $(LEVEL_2_EXP_F_4)

LEVEL_2_EXP_F_5=given-tests/level2-exp-f-5.txt
check-level-2-f-5: pagefault
	@given-tests/check.pl 5 $(LEVEL_2_INPUT) $(LEVEL_2_EXP_F_5)

LEVEL_2_EXP_F_6=given-tests/level2-exp-f-6.txt
check-level-2-f-6: pagefault
	@given-tests/check.pl 6 $(LEVEL_2_INPUT) $(LEVEL_2_EXP_F_6)

LEVEL_2_EXP_F_7=given-tests/level2-exp-f-7.txt
check-level-2-f-7: pagefault
	@given-tests/check.pl 7 $(LEVEL_2_INPUT) $(LEVEL_2_EXP_F_7)

###############################################
# Tests - Level 3
###############################################
LEVEL_3_INPUT=given-tests/level3.txt
check-level-3: pagefault banner_3 \
	check-level-3-f-0 check-level-3-f-1 check-level-3-f-2 check-level-3-f-3 \
	check-level-3-f-4 check-level-3-f-5 check-level-3-f-6 check-level-3-f-7

banner_3:
	@echo ""
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@echo "mmmmmmmmm Level 3 Tests mmmmmmmmmmm"
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@sleep 1

LEVEL_3_EXP_F_0=given-tests/level3-exp-f-0.txt
check-level-3-f-0: pagefault
	@given-tests/check.pl 0 $(LEVEL_3_INPUT) $(LEVEL_3_EXP_F_0)

LEVEL_3_EXP_F_1=given-tests/level3-exp-f-1.txt
check-level-3-f-1: pagefault
	@given-tests/check.pl 1 $(LEVEL_3_INPUT) $(LEVEL_3_EXP_F_1)

LEVEL_3_EXP_F_2=given-tests/level3-exp-f-2.txt
check-level-3-f-2: pagefault
	@given-tests/check.pl 2 $(LEVEL_3_INPUT) $(LEVEL_3_EXP_F_2)

LEVEL_3_EXP_F_3=given-tests/level3-exp-f-3.txt
check-level-3-f-3: pagefault
	@given-tests/check.pl 3 $(LEVEL_3_INPUT) $(LEVEL_3_EXP_F_3)

LEVEL_3_EXP_F_4=given-tests/level3-exp-f-4.txt
check-level-3-f-4: pagefault
	@given-tests/check.pl 4 $(LEVEL_3_INPUT) $(LEVEL_3_EXP_F_4)

LEVEL_3_EXP_F_5=given-tests/level3-exp-f-5.txt
check-level-3-f-5: pagefault
	@given-tests/check.pl 5 $(LEVEL_3_INPUT) $(LEVEL_3_EXP_F_5)

LEVEL_3_EXP_F_6=given-tests/level3-exp-f-6.txt
check-level-3-f-6: pagefault
	@given-tests/check.pl 6 $(LEVEL_3_INPUT) $(LEVEL_3_EXP_F_6)

LEVEL_3_EXP_F_7=given-tests/level3-exp-f-7.txt
check-level-3-f-7: pagefault
	@given-tests/check.pl 7 $(LEVEL_3_INPUT) $(LEVEL_3_EXP_F_7)


###############################################
# Tests - Level 4
###############################################
LEVEL_4_INPUT=given-tests/level4.txt
check-level-4: pagefault banner_4 \
	check-level-4-f-0 check-level-4-f-1 check-level-4-f-2 check-level-4-f-3 \
	check-level-4-f-4 check-level-4-f-5 check-level-4-f-6 check-level-4-f-7

banner_4:
	@echo ""
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@echo "mmmmmmmmm Level 4 Tests mmmmmmmmmmm"
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@sleep 1

LEVEL_4_EXP_F_0=given-tests/level4-exp-f-0.txt
check-level-4-f-0: pagefault
	@given-tests/check.pl 0 $(LEVEL_4_INPUT) $(LEVEL_4_EXP_F_0)

LEVEL_4_EXP_F_1=given-tests/level4-exp-f-1.txt
check-level-4-f-1: pagefault
	@given-tests/check.pl 1 $(LEVEL_4_INPUT) $(LEVEL_4_EXP_F_1)

LEVEL_4_EXP_F_2=given-tests/level4-exp-f-2.txt
check-level-4-f-2: pagefault
	@given-tests/check.pl 2 $(LEVEL_4_INPUT) $(LEVEL_4_EXP_F_2)

LEVEL_4_EXP_F_3=given-tests/level4-exp-f-3.txt
check-level-4-f-3: pagefault
	@given-tests/check.pl 3 $(LEVEL_4_INPUT) $(LEVEL_4_EXP_F_3)

LEVEL_4_EXP_F_4=given-tests/level4-exp-f-4.txt
check-level-4-f-4: pagefault
	@given-tests/check.pl 4 $(LEVEL_4_INPUT) $(LEVEL_4_EXP_F_4)

LEVEL_4_EXP_F_5=given-tests/level4-exp-f-5.txt
check-level-4-f-5: pagefault
	@given-tests/check.pl 5 $(LEVEL_4_INPUT) $(LEVEL_4_EXP_F_5)

LEVEL_4_EXP_F_6=given-tests/level4-exp-f-6.txt
check-level-4-f-6: pagefault
	@given-tests/check.pl 6 $(LEVEL_4_INPUT) $(LEVEL_4_EXP_F_6)

LEVEL_4_EXP_F_7=given-tests/level4-exp-f-7.txt
check-level-4-f-7: pagefault
	@given-tests/check.pl 7 $(LEVEL_4_INPUT) $(LEVEL_4_EXP_F_7)


###############################################
# Tests - Level 5
###############################################
LEVEL_5_INPUT=given-tests/level5.txt
check-level-5: pagefault banner_5 \
	check-level-5-f-0 check-level-5-f-1 check-level-5-f-2 check-level-5-f-3 \
	check-level-5-f-4 check-level-5-f-5 check-level-5-f-6 check-level-5-f-7

banner_5:
	@echo ""
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@echo "mmmmmmmmm Level 5 Tests mmmmmmmmmmm"
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@sleep 1

LEVEL_5_EXP_F_0=given-tests/level5-exp-f-0.txt
check-level-5-f-0: pagefault
	@given-tests/check.pl 0 $(LEVEL_5_INPUT) $(LEVEL_5_EXP_F_0)

LEVEL_5_EXP_F_1=given-tests/level5-exp-f-1.txt
check-level-5-f-1: pagefault
	@given-tests/check.pl 1 $(LEVEL_5_INPUT) $(LEVEL_5_EXP_F_1)

LEVEL_5_EXP_F_2=given-tests/level5-exp-f-2.txt
check-level-5-f-2: pagefault
	@given-tests/check.pl 2 $(LEVEL_5_INPUT) $(LEVEL_5_EXP_F_2)

LEVEL_5_EXP_F_3=given-tests/level5-exp-f-3.txt
check-level-5-f-3: pagefault
	@given-tests/check.pl 3 $(LEVEL_5_INPUT) $(LEVEL_5_EXP_F_3)

LEVEL_5_EXP_F_4=given-tests/level5-exp-f-4.txt
check-level-5-f-4: pagefault
	@given-tests/check.pl 4 $(LEVEL_5_INPUT) $(LEVEL_5_EXP_F_4)

LEVEL_5_EXP_F_5=given-tests/level5-exp-f-5.txt
check-level-5-f-5: pagefault
	@given-tests/check.pl 5 $(LEVEL_5_INPUT) $(LEVEL_5_EXP_F_5)

LEVEL_5_EXP_F_6=given-tests/level5-exp-f-6.txt
check-level-5-f-6: pagefault
	@given-tests/check.pl 6 $(LEVEL_5_INPUT) $(LEVEL_5_EXP_F_6)

LEVEL_5_EXP_F_7=given-tests/level5-exp-f-7.txt
check-level-5-f-7: pagefault
	@given-tests/check.pl 7 $(LEVEL_5_INPUT) $(LEVEL_5_EXP_F_7)


###############################################
# Tests - Level 6
###############################################
LEVEL_6_INPUT=given-tests/level6.txt
check-level-6: pagefault banner_6 \
	check-level-6-f-0 check-level-6-f-1 check-level-6-f-2 check-level-6-f-3 \
	check-level-6-f-4 check-level-6-f-5 check-level-6-f-6 check-level-6-f-7

banner_6:
	@echo ""
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@echo "mmmmmmmmm Level 6 Tests mmmmmmmmmmm"
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@sleep 1

LEVEL_6_EXP_F_0=given-tests/level6-exp-f-0.txt
check-level-6-f-0: pagefault
	@given-tests/check.pl 0 $(LEVEL_6_INPUT) $(LEVEL_6_EXP_F_0)

LEVEL_6_EXP_F_1=given-tests/level6-exp-f-1.txt
check-level-6-f-1: pagefault
	@given-tests/check.pl 1 $(LEVEL_6_INPUT) $(LEVEL_6_EXP_F_1)

LEVEL_6_EXP_F_2=given-tests/level6-exp-f-2.txt
check-level-6-f-2: pagefault
	@given-tests/check.pl 2 $(LEVEL_6_INPUT) $(LEVEL_6_EXP_F_2)

LEVEL_6_EXP_F_3=given-tests/level6-exp-f-3.txt
check-level-6-f-3: pagefault
	@given-tests/check.pl 3 $(LEVEL_6_INPUT) $(LEVEL_6_EXP_F_3)

LEVEL_6_EXP_F_4=given-tests/level6-exp-f-4.txt
check-level-6-f-4: pagefault
	@given-tests/check.pl 4 $(LEVEL_6_INPUT) $(LEVEL_6_EXP_F_4)

LEVEL_6_EXP_F_5=given-tests/level6-exp-f-5.txt
check-level-6-f-5: pagefault
	@given-tests/check.pl 5 $(LEVEL_6_INPUT) $(LEVEL_6_EXP_F_5)

LEVEL_6_EXP_F_6=given-tests/level6-exp-f-6.txt
check-level-6-f-6: pagefault
	@given-tests/check.pl 6 $(LEVEL_6_INPUT) $(LEVEL_6_EXP_F_6)

LEVEL_6_EXP_F_7=given-tests/level6-exp-f-7.txt
check-level-6-f-7: pagefault
	@given-tests/check.pl 7 $(LEVEL_6_INPUT) $(LEVEL_6_EXP_F_7)


###############################################
# Tests - Level 7
###############################################
LEVEL_7_INPUT=given-tests/level7.txt
check-level-7: pagefault banner_7 \
	check-level-7-f-0 check-level-7-f-1 check-level-7-f-2 check-level-7-f-3 \
	check-level-7-f-4 check-level-7-f-5 check-level-7-f-6 check-level-7-f-7

banner_7:
	@echo ""
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@echo "mmmmmmmmm Level 7 Tests mmmmmmmmmmm"
	@echo "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"
	@sleep 1

LEVEL_7_EXP_F_0=given-tests/level7-exp-f-0.txt
check-level-7-f-0: pagefault
	@given-tests/check.pl 0 $(LEVEL_7_INPUT) $(LEVEL_7_EXP_F_0)

LEVEL_7_EXP_F_1=given-tests/level7-exp-f-1.txt
check-level-7-f-1: pagefault
	@given-tests/check.pl 1 $(LEVEL_7_INPUT) $(LEVEL_7_EXP_F_1)

LEVEL_7_EXP_F_2=given-tests/level7-exp-f-2.txt
check-level-7-f-2: pagefault
	@given-tests/check.pl 2 $(LEVEL_7_INPUT) $(LEVEL_7_EXP_F_2)

LEVEL_7_EXP_F_3=given-tests/level7-exp-f-3.txt
check-level-7-f-3: pagefault
	@given-tests/check.pl 3 $(LEVEL_7_INPUT) $(LEVEL_7_EXP_F_3)

LEVEL_7_EXP_F_4=given-tests/level7-exp-f-4.txt
check-level-7-f-4: pagefault
	@given-tests/check.pl 4 $(LEVEL_7_INPUT) $(LEVEL_7_EXP_F_4)

LEVEL_7_EXP_F_5=given-tests/level7-exp-f-5.txt
check-level-7-f-5: pagefault
	@given-tests/check.pl 5 $(LEVEL_7_INPUT) $(LEVEL_7_EXP_F_5)

LEVEL_7_EXP_F_6=given-tests/level7-exp-f-6.txt
check-level-7-f-6: pagefault
	@given-tests/check.pl 6 $(LEVEL_7_INPUT) $(LEVEL_7_EXP_F_6)

LEVEL_7_EXP_F_7=given-tests/level7-exp-f-7.txt
check-level-7-f-7: pagefault
	@given-tests/check.pl 7 $(LEVEL_7_INPUT) $(LEVEL_7_EXP_F_7)

